/**
 * <p>Title: SIGEN</p>
 *
 * suporte@sigensistemas.com.br</p>
 *
 * @author P. Boaventura (SIGEN)
 * @version 1.0
 */
package com.sigen.ecf.view;

import com.sigen.ecf.model.bean.BeanCliente;
import com.sigen.ecf.model.bean.BeanCondicaoPagamento;
import com.sigen.ecf.persistencia.dao.impl.DAOCondicaoPagamento;
import com.sigen.ecf.view.util.UTILBiblioteca;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import nlink.win32.DllClass;
import nlink.win32.DllMethod;

public class VIEWSelecionarCondicaoPagamento extends javax.swing.JDialog {

    @DllClass
    public interface User32 {

        @DllMethod
        int BlockInput(boolean fBlock);
    }
    public boolean cancelado = true;
    private List<BeanCondicaoPagamento> lsCondicaoPagamento;
    private BigDecimal valorCompra;
    private BigDecimal valorDesconto;
    private BigDecimal valorReceber;
    private Integer numeroParcelas;
    private BeanCliente beanCliente;
    private Map mpParametros;

    public VIEWSelecionarCondicaoPagamento(java.awt.Frame parent, boolean modal, BigDecimal valorCompra, BigDecimal valorDesconto, BigDecimal valorReceber, Map parametros) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cancelado = true;
        this.valorCompra = valorCompra;
        this.valorDesconto = valorDesconto;
        this.valorReceber = valorReceber;
        this.mpParametros = parametros;
        this.beanCliente = parametros.get("BeanCliente") != null ? (BeanCliente) parametros.get("BeanCliente") : null;

        configurarComportamentoENTER();
        preencerCombo();
        preencherValores();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        CancelaAction cancelaAction = new CancelaAction();
        btnCancela.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancelaAction");
        btnCancela.getActionMap().put("cancelaAction", cancelaAction);

        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResumoVenda = new javax.swing.JPanel();
        labelDesconto = new javax.swing.JLabel();
        labelTotalReceber = new javax.swing.JLabel();
        labelDescricaoTotalVenda = new javax.swing.JLabel();
        labelTotalVenda = new javax.swing.JLabel();
        labelDescricaoDesconto = new javax.swing.JLabel();
        labelDescricaoTotalReceber = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbbCondicaoPagamento = new javax.swing.JComboBox();
        panelBotoes = new javax.swing.JPanel();
        btnConfirma = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Condicao de Pagamento");

        panelResumoVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumo da Venda:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        panelResumoVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelResumoVenda.setPreferredSize(new java.awt.Dimension(200, 220));

        labelDesconto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDesconto.setForeground(new java.awt.Color(255, 0, 0));
        labelDesconto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDesconto.setText("0.00");

        labelTotalReceber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotalReceber.setForeground(new java.awt.Color(0, 0, 255));
        labelTotalReceber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalReceber.setText("0.00");

        labelDescricaoTotalVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDescricaoTotalVenda.setForeground(new java.awt.Color(0, 0, 255));
        labelDescricaoTotalVenda.setText("Total Venda:");

        labelTotalVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotalVenda.setForeground(new java.awt.Color(0, 0, 255));
        labelTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalVenda.setText("0.00");

        labelDescricaoDesconto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDescricaoDesconto.setForeground(new java.awt.Color(255, 0, 0));
        labelDescricaoDesconto.setText("Desconto:");

        labelDescricaoTotalReceber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDescricaoTotalReceber.setForeground(new java.awt.Color(0, 0, 255));
        labelDescricaoTotalReceber.setText("Total a Receber:");

        javax.swing.GroupLayout panelResumoVendaLayout = new javax.swing.GroupLayout(panelResumoVenda);
        panelResumoVenda.setLayout(panelResumoVendaLayout);
        panelResumoVendaLayout.setHorizontalGroup(
            panelResumoVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumoVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResumoVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDescricaoTotalVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDescricaoDesconto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDescricaoTotalReceber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelResumoVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDesconto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalReceber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResumoVendaLayout.setVerticalGroup(
            panelResumoVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumoVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResumoVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalVenda)
                    .addComponent(labelDescricaoTotalVenda))
                .addGroup(panelResumoVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResumoVendaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelDescricaoDesconto))
                    .addGroup(panelResumoVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDesconto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResumoVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricaoTotalReceber)
                    .addComponent(labelTotalReceber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Condição Pagamento");

        cbbCondicaoPagamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbbCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotoes.setBackground(new Color(255,255,255,0));
        panelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBotoes.setMinimumSize(new java.awt.Dimension(261, 30));
        panelBotoes.setPreferredSize(new java.awt.Dimension(261, 30));

        btnConfirma.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotoes/botaoConfirmar.png"))); // NOI18N
        btnConfirma.setText("Confirma (ENTER)");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        btnCancela.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotoes/botaoCancelar.png"))); // NOI18N
        btnCancela.setText("Cancela (ESC)");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancela)
                .addGap(62, 62, 62))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirma)
                    .addComponent(btnCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResumoVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResumoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
    dispose();
}//GEN-LAST:event_btnCancelaActionPerformed

private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
    confirmar();
}//GEN-LAST:event_btnConfirmaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JComboBox cbbCondicaoPagamento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDesconto;
    private javax.swing.JLabel labelDescricaoDesconto;
    private javax.swing.JLabel labelDescricaoTotalReceber;
    private javax.swing.JLabel labelDescricaoTotalVenda;
    private javax.swing.JLabel labelTotalReceber;
    private javax.swing.JLabel labelTotalVenda;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelResumoVenda;
    // End of variables declaration//GEN-END:variables

    private class ConfirmaAction extends AbstractAction {

        public ConfirmaAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            confirmar();
        }
    }

    private class CancelaAction extends AbstractAction {

        public CancelaAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
        }
    }

    private void configurarComportamentoENTER() {
        cbbCondicaoPagamento.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnConfirma.requestFocus();
                }
            }
        });

        btnConfirma.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    confirmar();
                }
            }
        });
    }

    private void confirmar() {
        selecionarNumeroParcelas();
        if (numeroParcelas != null) {
            selecionarFormaPagamento();
        }
    }

    private void selecionarFormaPagamento() {
        this.setVisible(false);
        mpParametros.put("BeanCliente", beanCliente != null ? beanCliente : null);
        VIEWSelecionarFormaPagamento selecionarFormaPagamento = new VIEWSelecionarFormaPagamento(null, true, getCondicaoPagamento(), valorReceber, valorDesconto, numeroParcelas, mpParametros);
        selecionarFormaPagamento.setVisible(true);
        if (!selecionarFormaPagamento.cancelado) {
            cancelado = false;
            dispose();
        }
        cbbCondicaoPagamento.requestFocus();
    }

    private void selecionarNumeroParcelas() {
        /* Número de parcelas conforme a condição de pagamento */
        int maxParcelasCondicao = ((BeanCondicaoPagamento) cbbCondicaoPagamento.getSelectedItem()).getParcelaMax();
        Integer[] opcoesParcelas = new Integer[maxParcelasCondicao];
        numeroParcelas = null;
        if (opcoesParcelas.length > 1) {
            for (int i = 0; i < maxParcelasCondicao; i++) {
                opcoesParcelas[i] = i + 1;
            }
            numeroParcelas = (Integer) JOptionPane.showInputDialog(this, "Parcelamento", "Parcelas", JOptionPane.PLAIN_MESSAGE, null, opcoesParcelas, 1);
        } else {
            numeroParcelas = 1;
        }
    }

    private BeanCondicaoPagamento getCondicaoPagamento() {
        return (BeanCondicaoPagamento) cbbCondicaoPagamento.getSelectedItem();
    }

    private void preencerCombo() {
        DefaultComboBoxModel box = new DefaultComboBoxModel();
        lsCondicaoPagamento = new DAOCondicaoPagamento().pesquisa(new BeanCondicaoPagamento());
        // Ordenar crescente
        Collections.sort(lsCondicaoPagamento);

        // Adicionando ao modelo
        for (BeanCondicaoPagamento condicaoPagamento : lsCondicaoPagamento) {
            box.addElement(condicaoPagamento);
        }

        // Adicionando a combo
        cbbCondicaoPagamento.setModel(box);
    }

    private void preencherValores() {
        labelTotalVenda.setText(UTILBiblioteca.formatoDecimal("V", valorCompra));
        labelDesconto.setText(UTILBiblioteca.formatoDecimal("V", valorDesconto));
        labelTotalReceber.setText(UTILBiblioteca.formatoDecimal("V", valorReceber));
    }

    public Map getParametros() {
        return mpParametros;
    }
}
