/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DadosCheque1.java
 *
 * Created on 22/02/2012, 13:03:41
 */
package com.sigen.ecf.view;

import com.sigen.ecf.vo.VOCheque;
import com.sigen.ecf.view.util.LimitedDocumentTextField;
import com.sigen.ecf.view.util.UTILBiblioteca;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Administrador
 */
public class VIEWInserirDadosCheque extends javax.swing.JDialog {

    public boolean cancelado = true;
    private List<Date> lsDataPagamento;

    public VIEWInserirDadosCheque(java.awt.Frame parent, boolean modal, List<Date> lsData) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        configurarLimitedTextField();
        configurarComportamentoENTER();
        this.lsDataPagamento = lsData;
        preencherCombo();

        CancelaAction cancelaAction = new CancelaAction();
        botaoCancela.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancelaAction");
        botaoCancela.getActionMap().put("cancelaAction", cancelaAction);


        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotoes = new javax.swing.JPanel();
        botaoConfirma = new javax.swing.JButton();
        botaoCancela = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelValor = new javax.swing.JPanel();
        lblBanco = new javax.swing.JLabel();
        txtBanco = new javax.swing.JFormattedTextField();
        lblAgencia = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JFormattedTextField();
        lblContaCorrente = new javax.swing.JLabel();
        txtContaCorrente = new javax.swing.JFormattedTextField();
        panelValor2 = new javax.swing.JPanel();
        lblNumeroCheque = new javax.swing.JLabel();
        txtNumeroCheque = new javax.swing.JFormattedTextField();
        cbbDataPagamento = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBotoes.setBackground(new Color(255,255,255,0));

        botaoConfirma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotoes/botaoConfirmar.png"))); // NOI18N
        botaoConfirma.setText("Confirma (ENTER)");
        botaoConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmaActionPerformed(evt);
            }
        });

        botaoCancela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgBotoes/botaoCancelar.png"))); // NOI18N
        botaoCancela.setText("Cancela (ESC)");
        botaoCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoConfirma)
                .addGap(18, 18, 18)
                .addComponent(botaoCancela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirma)
                    .addComponent(botaoCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cheque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        panelValor.setBackground(new Color(255,255,255,0));

        lblBanco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBanco.setText("Banco");

        txtBanco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBanco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblAgencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAgencia.setText("Agência");

        txtAgencia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAgencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblContaCorrente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContaCorrente.setText("Conta Corrente");

        txtContaCorrente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContaCorrente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelValorLayout = new javax.swing.GroupLayout(panelValor);
        panelValor.setLayout(panelValorLayout);
        panelValorLayout.setHorizontalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContaCorrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        panelValorLayout.setVerticalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValorLayout.createSequentialGroup()
                        .addComponent(lblBanco)
                        .addGap(5, 5, 5)
                        .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelValorLayout.createSequentialGroup()
                        .addComponent(lblAgencia)
                        .addGap(5, 5, 5)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelValorLayout.createSequentialGroup()
                        .addComponent(lblContaCorrente)
                        .addGap(5, 5, 5)
                        .addComponent(txtContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelValor2.setBackground(new Color(255,255,255,0));

        lblNumeroCheque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumeroCheque.setText("Número Cheque");

        txtNumeroCheque.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumeroCheque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cbbDataPagamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbbDataPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data de Pagamento");

        javax.swing.GroupLayout panelValor2Layout = new javax.swing.GroupLayout(panelValor2);
        panelValor2.setLayout(panelValor2Layout);
        panelValor2Layout.setHorizontalGroup(
            panelValor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNumeroCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumeroCheque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelValor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        panelValor2Layout.setVerticalGroup(
            panelValor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValor2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelValor2Layout.createSequentialGroup()
                        .addComponent(lblNumeroCheque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botaoConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmaActionPerformed
    cancelado = true;
    dispose();
}//GEN-LAST:event_botaoConfirmaActionPerformed

private void botaoCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelaActionPerformed
    dispose();
}//GEN-LAST:event_botaoCancelaActionPerformed

    private class ConfirmaAction extends AbstractAction {

        public ConfirmaAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            cancelado = true;
            dispose();
        }
    }

    private class CancelaAction extends AbstractAction {

        public CancelaAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancela;
    private javax.swing.JButton botaoConfirma;
    private javax.swing.JComboBox cbbDataPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblContaCorrente;
    private javax.swing.JLabel lblNumeroCheque;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelValor;
    private javax.swing.JPanel panelValor2;
    private javax.swing.JFormattedTextField txtAgencia;
    private javax.swing.JFormattedTextField txtBanco;
    private javax.swing.JFormattedTextField txtContaCorrente;
    private javax.swing.JFormattedTextField txtNumeroCheque;
    // End of variables declaration//GEN-END:variables

    private void configurarComportamentoENTER() {

        txtBanco.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (validarCampo(txtBanco.getText().trim())) {
                        txtAgencia.requestFocus();
                    } else {
                        txtBanco.requestFocus();
                    }
                }
            }
        });

        txtAgencia.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (validarCampo(txtAgencia.getText().trim())) {
                        txtContaCorrente.requestFocus();
                    } else {
                        txtAgencia.requestFocus();
                    }
                }
            }
        });

        txtContaCorrente.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (validarCampo(txtContaCorrente.getText().trim())) {
                        txtNumeroCheque.requestFocus();
                    } else {
                        txtContaCorrente.requestFocus();
                    }
                }
            }
        });

        txtNumeroCheque.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if (validarCampo(txtNumeroCheque.getText().trim())) {
                        cbbDataPagamento.requestFocus();
                    } else {
                        txtNumeroCheque.requestFocus();
                    }
                }
            }
        });

        cbbDataPagamento.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    botaoConfirma.requestFocus();
                }
            }
        });

        botaoConfirma.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    cancelado = false;
                    dispose();
                }
            }
        });

        botaoCancela.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    dispose();
                }
            }
        });
    }

    private void configurarLimitedTextField() {
        /*
         * limitar quantidade de caracteres dos campos
         */
        txtBanco.setDocument(new LimitedDocumentTextField(3));
        txtAgencia.setDocument(new LimitedDocumentTextField(6));
        txtContaCorrente.setDocument(new LimitedDocumentTextField(10));
        txtNumeroCheque.setDocument(new LimitedDocumentTextField(10));
    }

    private boolean validarCampo(String campo) {
        /*
         * Validar campo com apenas inteiro
         */
        if (UTILBiblioteca.regexInteger(campo)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Campo deve conter apenas números", "Aviso do Sistema", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    private void preencherCombo() {
        DefaultComboBoxModel box = new DefaultComboBoxModel();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        // Ordenar crescente
        Collections.sort(lsDataPagamento);

        // Adicionando ao modelo
        for (Date data : lsDataPagamento) {
            box.addElement(sdf.format(data));
        }

        // Adicionando a combo
        cbbDataPagamento.setModel(box);
    }

    public VOCheque getDadosCheque() {
        VOCheque cheque = new VOCheque();
        cheque.setCodBanco(txtBanco.getText().trim());
        cheque.setCodAgencia(txtAgencia.getText().trim());
        cheque.setContaCorrente(txtContaCorrente.getText().trim());
        cheque.setNumeroCheque(txtNumeroCheque.getText().trim());
        int i = cbbDataPagamento.getSelectedIndex();
        cheque.setData(lsDataPagamento.get(i));

        return cheque;
    }
}
